name: name-to-ethnicity web app action

on:
  push:
    branches:
      - server

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: name-ethnicity-classifier
          password: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create image from repository
        run: |
          docker build -t ghcr.io/name-ethnicity-classifier/nec-webapp-client .
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/name-ethnicity-classifier/nec-webapp-client:latest

