name: name-to-ethnicity web app action

on:
  push:
    branches:
      - server

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image and push to GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/nec-webapp-client:latest
